#!/bin/bash
#SBATCH -J Unknown
#SBATCH -p general
#SBATCH -e Unknown_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=xuexiao@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --mem=200gb
#SBATCH --time=10:00:00

export PATH="/N/slate/xuexiao/velocyto/velocyto/bin:$PATH"

module unload python
module load python
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8
source activate velocyto


featureCounts -O -M --primary -p --largestOverlap -T 4 -B -s 2 -R CORE \
-a /N/slate/xuexiao/Genome/GRCh38/Homo_sapiens.GRCh38.104.gtf \
-o /N/slate/xuexiao/cJun_CREB1_ChIP/RNA_reads/CREB1_geneCounts.tsv \
/N/slate/xuexiao/cJun_CREB1_ChIP/Align/OV3_CREB1KD_3_S6_new_Aligned.sortedByCoord.out.bam \
/N/slate/xuexiao/cJun_CREB1_ChIP/Align/OV3_CREB1KD_2_S5_new_Aligned.sortedByCoord.out.bam \
/N/slate/xuexiao/cJun_CREB1_ChIP/Align/OV3_CREB1KD_1_S4_new_Aligned.sortedByCoord.out.bam \
/N/slate/xuexiao/cJun_CREB1_ChIP/Align/OV3_scr_3_S3_new_Aligned.sortedByCoord.out.bam \
/N/slate/xuexiao/cJun_CREB1_ChIP/Align/OV3_scr_2_S2_new_Aligned.sortedByCoord.out.bam \
/N/slate/xuexiao/cJun_CREB1_ChIP/Align/OV3_scr_1_S1_new_Aligned.sortedByCoord.out.bam 


source deactivate

