#!/bin/bash
#SBATCH -J HISAT2_featureCount
#SBATCH -p general
#SBATCH -e CREB1_HISAT2_featureCount_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=xuexiao@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --time=10:00:00


export PATH="/N/slate/xuexiao/velocyto/velocyto/bin:$PATH"

module unload python
module load python
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8
source activate velocyto

###################### Download index ###############################
#cd /N/slate/xuexiao/Genome/GRCh38
#wget https://genome-idx.s3.amazonaws.com/hisat/grch38_genome.tar.gz
#tar -zxvf grch38_genome.tar.gz

cd /N/slate/xuexiao/cJun_CREB1_ChIP/Align

hisat2 -q --rna-strandness F --new-summary \
--summary-file /N/slate/xuexiao/cJun_CREB1_ChIP/Align/hisat2_summary.tsv \
--un-gz /N/slate/xuexiao/cJun_CREB1_ChIP/Align/hisat2_unmapped.tsv.gz \
-p 4 --mm -t -x /N/slate/xuexiao/Genome/GRCh38/grch38/genome -1 /N/slate/xuexiao/cJun_CREB1_ChIP/Clean/OV3_scr_1_S1_R1_trim_paired.fastq -2 /N/slate/xuexiao/cJun_CREB1_ChIP/Clean/OV3_scr_1_S1_R2_trim_paired.fastq -S OV3_scr_1_S1.sam

hisat2 -q --rna-strandness F --new-summary \
--summary-file /N/slate/xuexiao/cJun_CREB1_ChIP/Align/hisat2_summary.tsv \
--un-gz /N/slate/xuexiao/cJun_CREB1_ChIP/Align/hisat2_unmapped.tsv.gz \
-p 4 --mm -t -x /N/slate/xuexiao/Genome/GRCh38/grch38/genome -1 /N/slate/xuexiao/cJun_CREB1_ChIP/Clean/OV3_scr_2_S2_R1_trim_paired.fastq -2 /N/slate/xuexiao/cJun_CREB1_ChIP/Clean/OV3_scr_2_S2_R2_trim_paired.fastq -S OV3_scr_2_S2.sam

hisat2 -q --rna-strandness F --new-summary \
--summary-file /N/slate/xuexiao/cJun_CREB1_ChIP/Align/hisat2_summary.tsv \
--un-gz /N/slate/xuexiao/cJun_CREB1_ChIP/Align/hisat2_unmapped.tsv.gz \
-p 4 --mm -t -x /N/slate/xuexiao/Genome/GRCh38/grch38/genome -1 /N/slate/xuexiao/cJun_CREB1_ChIP/Clean/OV3_scr_3_S3_R1_trim_paired.fastq -2 /N/slate/xuexiao/cJun_CREB1_ChIP/Clean/OV3_scr_3_S3_R2_trim_paired.fastq -S OV3_scr_3_S3.sam

hisat2 -q --rna-strandness F --new-summary \
--summary-file /N/slate/xuexiao/cJun_CREB1_ChIP/Align/hisat2_summary.tsv \
--un-gz /N/slate/xuexiao/cJun_CREB1_ChIP/Align/hisat2_unmapped.tsv.gz \
-p 4 --mm -t -x /N/slate/xuexiao/Genome/GRCh38/grch38/genome -1 /N/slate/xuexiao/cJun_CREB1_ChIP/Clean/OV3_CREB1KD_1_S4_R1_trim_paired.fastq -2 /N/slate/xuexiao/cJun_CREB1_ChIP/Clean/OV3_CREB1KD_1_S4_R2_trim_paired.fastq -S OV3_CREB1KD_1_S4.sam

hisat2 -q --rna-strandness F --new-summary \
--summary-file /N/slate/xuexiao/cJun_CREB1_ChIP/Align/hisat2_summary.tsv \
--un-gz /N/slate/xuexiao/cJun_CREB1_ChIP/Align/hisat2_unmapped.tsv.gz \
-p 4 --mm -t -x /N/slate/xuexiao/Genome/GRCh38/grch38/genome -1 /N/slate/xuexiao/cJun_CREB1_ChIP/Clean/OV3_CREB1KD_2_S5_R1_trim_paired.fastq -2 /N/slate/xuexiao/cJun_CREB1_ChIP/Clean/OV3_CREB1KD_2_S5_R2_trim_paired.fastq -S OV3_CREB1KD_2_S5.sam

hisat2 -q --rna-strandness F --new-summary \
--summary-file /N/slate/xuexiao/cJun_CREB1_ChIP/Align/hisat2_summary.tsv \
--un-gz /N/slate/xuexiao/cJun_CREB1_ChIP/Align/hisat2_unmapped.tsv.gz \
-p 4 --mm -t -x /N/slate/xuexiao/Genome/GRCh38/grch38/genome -1 /N/slate/xuexiao/cJun_CREB1_ChIP/Clean/OV3_CREB1KD_3_S6_R1_trim_paired.fastq -2 /N/slate/xuexiao/cJun_CREB1_ChIP/Clean/OV3_CREB1KD_3_S6_R2_trim_paired.fastq -S OV3_CREB1KD_3_S6.sam


samtools sort OV3_scr_1_S1.sam > OV3_scr_1_S1_sorted.bam
samtools index OV3_scr_1_S1_sorted.bam
samtools sort OV3_scr_2_S2.sam > OV3_scr_2_S2_sorted.bam
samtools index OV3_scr_2_S2_sorted.bam
samtools sort OV3_scr_3_S3.sam > OV3_scr_3_S3_sorted.bam
samtools index OV3_scr_3_S3_sorted.bam

samtools sort OV3_CREB1KD_1_S4.sam > OV3_CREB1KD_1_S4_sorted.bam
samtools index OV3_CREB1KD_1_S4_sorted.bam
samtools sort OV3_CREB1KD_2_S5.sam > OV3_CREB1KD_2_S5_sorted.bam
samtools index OV3_CREB1KD_2_S5_sorted.bam
samtools sort OV3_CREB1KD_3_S6.sam > OV3_CREB1KD_3_S6_sorted.bam
samtools index OV3_CREB1KD_3_S6_sorted.bam

featureCounts -O -M --primary -p --largestOverlap -T 4 -B -s 2 -R CORE \
-a /N/slate/xuexiao/Genome/GRCh38/Homo_sapiens.GRCh38.104.gtf \
-o /N/slate/xuexiao/cJun_CREB1_ChIP/RNA_reads/CREB1_hisat2_geneCounts.tsv \
/N/slate/xuexiao/cJun_CREB1_ChIP/Align/OV3_CREB1KD_3_S6_sorted.bam \
/N/slate/xuexiao/cJun_CREB1_ChIP/Align/OV3_CREB1KD_2_S5_sorted.bam \
/N/slate/xuexiao/cJun_CREB1_ChIP/Align/OV3_CREB1KD_1_S4_sorted.bam \
/N/slate/xuexiao/cJun_CREB1_ChIP/Align/OV3_scr_3_S3_sorted.bam \
/N/slate/xuexiao/cJun_CREB1_ChIP/Align/OV3_scr_2_S2_sorted.bam \
/N/slate/xuexiao/cJun_CREB1_ChIP/Align/OV3_scr_1_S1_sorted.bam

source deactivate


