#!/bin/bash
#SBATCH -J STAR_index
#SBATCH -p general
#SBATCH -e STAR_index_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=xuexiao@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=200gb
#SBATCH --time=1:00:00

export PATH="/N/slate/xuexiao/velocyto/velocyto/bin:$PATH"

module unload python
module load python
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8
source activate velocyto

STAR --runThreadN 6 --runMode genomeGenerate --genomeDir /N/slate/xuexiao/Genome/GRCh38/rRNA_index \
--genomeFastaFiles /N/slate/xuexiao/Genome/GRCh38/Human_rRNA_repeats.fasta \
--genomeSAindexNbases 6

cd /N/slate/xuexiao/cJun_CREB1_ChIP/Align
export PATH=$PATH:/N/slate/xuexiao/STAR/STAR-2.7.7a/source/

STAR --runThreadN 6 --runMode alignReads --genomeDir /N/slate/xuexiao/Genome/GRCh38/rRNA_index \
--readFilesIn /N/slate/xuexiao/cJun_CREB1_ChIP/Clean/OV3_scr_1_S1_R1_trim_paired.fastq /N/slate/xuexiao/cJun_CREB1_ChIP/Clean/OV3_scr_1_S1_R2_trim_paired.fastq \
--twopassMode Basic \
--outSAMtype BAM SortedByCoordinate \
--outFileNamePrefix OV3_scr_1_rRNA_

